version: 2
default_settings: &default_settings
  docker:
    - image: circleci/node:10.19.0-stretch-browsers
  working_directory: ~/repo
jobs:
  run_puppeteer:
    <<: *default_settings
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-
            - yarn-packages-v1-
      - run: yarn install
      - save_cache:
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: run puppeteer
          command: node index.js
      - store_artifacts:
          path: ~/repo/example.png

workflows:
  version: 2
  awesome_workflows:
    jobs:
      - run_puppeteer
